# Generated by Django 4.0.6 on 2022-08-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RatePerPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rppBW', models.PositiveIntegerField()),
                ('rppC', models.PositiveIntegerField()),
            ],
        ),
    ]
