# Generated by Django 4.0.6 on 2022-08-24 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, null=True, unique=True)),
                ('username', models.CharField(max_length=150, null=True, unique=150)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=150)),
                ('accessno', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrintDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='media')),
                ('date_uploaded', models.DateField(auto_now_add=True)),
                ('copies', models.SmallIntegerField(default=1)),
                ('num_pages', models.SmallIntegerField(default=1)),
                ('colour', models.CharField(choices=[('BLACK_AND_WHITE', 'black_and_white'), ('COLOURED', 'coloured')], default='BLACK_AND_WHITE', max_length=20)),
                ('sides', models.CharField(choices=[('ONE_SIDED', 'one_sided'), ('DOUBLE_SIDED', 'double_sided')], default='ONE_SIDED', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('order_id', models.CharField(default='', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
            },
        ),
    ]
